services:
  db:
    container_name: db
    image: postgres
    restart: always
    ports:
      - 2345:5432
    env_file:
      - .env
    networks:
      - network
    volumes:
      - postgres:/var/lib/postgresql/data

  node_app:
    container_name: node_app
    build: ./back-end/
    ports:
      - 5000:5000
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - network

  app_react:
    build: ./front-end/
    container_name: app_react
    env_file:
      - .env
    networks:
      - network
    volumes:
      - build_react:/var/www/html

  nginx:
    build: ./nginx/
    container_name: nginx
    ports:
      - 80:80
    networks:
      - network
    volumes:
      - build_react:/var/www/html
    depends_on:
      - db
      - node_app
      - app_react

volumes:
  postgres:
  build_react:


networks:
  network:
    driver: bridge